#!/bin/sh

### BEGIN INIT INFO
# Provides: bluetooth
# Required-Start:    $ALL
# Required-Stop:     $local_fs $syslog $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Flower Daemon
### END INIT INFO

#Core Variables
NAME=flower

#Execute flower Script

CHDIR="/home/pi/Robinhood_Model"
FLOWER=" flower -A Task_Manager.celery"

case "$1" in
  start)
	echo -n "Starting flower on Task Manager Node\n"
	start-stop-daemon --start --pidfile /var/run/$NAME.pid \
	--chdir $CHDIR -b --make-pidfile --exec /usr/local/bin/celery --$FLOWER
	;;
  stop)
	echo -n "Stopping flower on Task Manager Node"
	start-stop-daemon --stop --quiet --oknodo \
	--pidfile /var/run/$NAME.pid
	rm -f /var/run/$NAME.pdi
	echo "$NAME"
	;;
esac

exit 0

